project_name: "advanced-knowledge-graph"

neo4j:
  uri: "bolt://localhost:7687"
  username: null
  password: null

llm:
  base_url: "http://localhost:11434/v1"  # Ollama
  api_key: "not-needed"                  # Für lokale APIs oft nicht nötig
  model: "qwen2.5:latest"                # Ihr bevorzugtes Modell

extractor:
  text_chunking: true
  chunk_size: 1000

processor:
  ner_model: "de_core_news_lg"
  ner_confidence_threshold: 0.8
  relation_confidence_threshold: 0.6
